# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_upLpaDXgnGpzZa85EMtWZ10eJEo5FW
"""

code = """
# ... Hangman code ...
"""
with open("hangman.py", "w") as f:
    f.write(code)